/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dbproject.Forms;
import dbproject.Connection;
import static dbproject.Connection.GetPayments;
import static dbproject.Connection.SendToServer;

import javax.swing.JOptionPane;

/**
 *
 * @author Jabarda
 */
public class ClientWindow extends javax.swing.JFrame {
        String id;
        String CardNumber;
        String [] Payments;
        String [] LicienceList;
        int[] price;
        String [] Bufprice;
        String [] Access;
    /**
     * Creates new form ClientWindowNew
     */
    public ClientWindow() {
        initComponents();
    }
    
    public void BuyFuncs(String From,String To,String Func, String price){
        int money = Integer.parseInt(MoneyLabel.getText())-Integer.parseInt(price);
        if (money>=0) SendToServer("B"+";"+id+";"+From+";"+To+";"+Func+";"+Integer.toString(money));
        else JOptionPane.showMessageDialog(null, "No money!");
        this.DataUpdate();
        
    }
    public void AddFunds(String amount, String CardNumber)
    {
        SendToServer("N"+";"+id+";"+amount+";"+CardNumber);
        this.DataUpdate();
    }
    public void SetId(String NewId, String Login)
    {
        id = new String(NewId);
        AccNameLabel.setText(Login);
    }
    public void DataUpdate(){
        String s=null;
        price = new int[10];
        s=SendToServer("M"+id);
        MoneyLabel.setText(s);
        Payments=GetPayments("P"+id);
        LicienceList=GetPayments("I"+id);
        Bufprice=GetPayments("C"+id);
        int i=0;
        while (!"end".equals(Bufprice[i])) {
            
            price[i]=Integer.parseInt(Bufprice[i]);
            i++;
        }
        Access=GetPayments("A"+id);
        Func1Button.setEnabled(false);
        Func2Button.setEnabled(false);
        Func3Button.setEnabled(false);
        i=0;
        while (!"end".equals(Access[i])) {
            if ("1".equals(Access[i])) Func1Button.setEnabled(true);
            if ("2".equals(Access[i])) Func2Button.setEnabled(true);
            if ("3".equals(Access[i])) Func3Button.setEnabled(true);
            i++;
        }
        
        
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AccNameLabel = new javax.swing.JLabel();
        PurchasesHistoryButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        LogoutButton = new javax.swing.JButton();
        Func1Button = new javax.swing.JButton();
        Func2Button = new javax.swing.JButton();
        Func3Button = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        MoneyLabel = new javax.swing.JLabel();
        AddFundsButton = new javax.swing.JButton();
        PaymentHistoryButton = new javax.swing.JButton();
        UpdateButton = new javax.swing.JButton();
        BuyFunc = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        AccNameLabel.setText("Account's name");

        PurchasesHistoryButton.setText("Purchases history");
        PurchasesHistoryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PurchasesHistoryButtonActionPerformed(evt);
            }
        });

        jLabel2.setText("account");

        LogoutButton.setText("Logout");
        LogoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutButtonActionPerformed(evt);
            }
        });

        Func1Button.setText("Function 1");
        Func1Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Func1ButtonActionPerformed(evt);
            }
        });

        Func2Button.setText("Function 2");
        Func2Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Func2ButtonActionPerformed(evt);
            }
        });

        Func3Button.setText("Function 3");
        Func3Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Func3ButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Money:");

        MoneyLabel.setText("NULL");

        AddFundsButton.setText("Add money");
        AddFundsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddFundsButtonActionPerformed(evt);
            }
        });

        PaymentHistoryButton.setText("Payment history");
        PaymentHistoryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PaymentHistoryButtonActionPerformed(evt);
            }
        });

        UpdateButton.setText("Update");
        UpdateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateButtonActionPerformed(evt);
            }
        });

        BuyFunc.setText("Buy Some");
        BuyFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuyFuncActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(MoneyLabel)
                            .addComponent(PaymentHistoryButton))
                        .addGap(18, 18, 18)
                        .addComponent(PurchasesHistoryButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(LogoutButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(UpdateButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Func1Button)
                                .addGap(18, 18, 18)
                                .addComponent(Func2Button)
                                .addGap(18, 18, 18)
                                .addComponent(Func3Button))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(99, 99, 99)
                                .addComponent(AddFundsButton)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(AccNameLabel)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BuyFunc)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(AccNameLabel)
                        .addComponent(jLabel2))
                    .addComponent(BuyFunc))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Func1Button)
                    .addComponent(Func2Button)
                    .addComponent(Func3Button))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 123, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(MoneyLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AddFundsButton))
                .addGap(37, 37, 37)
                .addComponent(UpdateButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LogoutButton)
                    .addComponent(PaymentHistoryButton)
                    .addComponent(PurchasesHistoryButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Func1ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Func1ButtonActionPerformed
        JOptionPane.showMessageDialog(null, "This function works!");        // TODO add your handling code here:
    }//GEN-LAST:event_Func1ButtonActionPerformed

    private void LogoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutButtonActionPerformed
            // TODO add your handling code here:
            LoginWindow Login = new LoginWindow();
            Login.setVisible(true);
            this.dispose();
    }//GEN-LAST:event_LogoutButtonActionPerformed

    private void Func2ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Func2ButtonActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "This function works!");
    }//GEN-LAST:event_Func2ButtonActionPerformed

    private void Func3ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Func3ButtonActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "This function works!");
    }//GEN-LAST:event_Func3ButtonActionPerformed

    private void UpdateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateButtonActionPerformed
        // TODO add your handling code here:
        this.DataUpdate();
    }//GEN-LAST:event_UpdateButtonActionPerformed

    private void PurchasesHistoryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PurchasesHistoryButtonActionPerformed
        LicienseList window = new LicienseList();
        int i=0;
        while (!"end".equals(LicienceList[i])) {window.ListFill(LicienceList[i]); i++;}
        window.setVisible(true);
        window.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        // TODO add your handling code here:
    }//GEN-LAST:event_PurchasesHistoryButtonActionPerformed

    private void PaymentHistoryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PaymentHistoryButtonActionPerformed
        // TODO add your handling code here:
        PaymentsList window = new PaymentsList();
        int i=0;
        while (!"end".equals(Payments[i])) {window.ListFill(Payments[i]); i++;}
        window.setVisible(true);
        window.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_PaymentHistoryButtonActionPerformed

    private void AddFundsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddFundsButtonActionPerformed
        // TODO add your handling code here:
        GetCardNumber window = new GetCardNumber();
        window.setClient(this);
        window.setVisible(true);
        window.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_AddFundsButtonActionPerformed

    private void BuyFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuyFuncActionPerformed
        // TODO add your handling code here:
        FuncBuying window = new FuncBuying();
        window.SetPrice(price);
        window.setClient(this);
        window.setVisible(true);
        window.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        
    }//GEN-LAST:event_BuyFuncActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClientWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClientWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClientWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClientWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new ClientWindow().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AccNameLabel;
    private javax.swing.JButton AddFundsButton;
    private javax.swing.JButton BuyFunc;
    private javax.swing.JButton Func1Button;
    private javax.swing.JButton Func2Button;
    private javax.swing.JButton Func3Button;
    private javax.swing.JButton LogoutButton;
    private javax.swing.JLabel MoneyLabel;
    private javax.swing.JButton PaymentHistoryButton;
    private javax.swing.JButton PurchasesHistoryButton;
    private javax.swing.JButton UpdateButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
